-- base de datos: vacunas (PostgreSQL)

-- Tabla de Vacunas
CREATE TABLE IF NOT EXISTS vaccines (
    id_vaccine INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    inventory INT DEFAULT 0,
    manufacturer VARCHAR(100),
    description TEXT,
    min_age_months INT,
    max_age_months INT
);

-- Tabla de Tutores
CREATE TABLE IF NOT EXISTS guardians (
    guardian_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    lastname VARCHAR(50),
    curp VARCHAR(18) UNIQUE,
    number BIGINT,
    mail VARCHAR(100),
    address VARCHAR(200),
    estado_civil VARCHAR(50),
    notes TEXT
);

-- Tabla de Trabajadores
CREATE TABLE IF NOT EXISTS workers (
    worker_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    lastname VARCHAR(100),
    role VARCHAR(20) CHECK (role IN ('Administrador', 'Almacen', 'Enfermero')),
    mail VARCHAR(100) UNIQUE,
    curp VARCHAR(18),
    address VARCHAR(250),
    birth_date DATE,
    password_hash VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de Pacientes
CREATE TABLE IF NOT EXISTS patients (
    patient_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    blood_type VARCHAR(3) CHECK (blood_type IN ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
    gender VARCHAR(10) CHECK (gender IN ('Masculino','Femenino')),
    nfc_token VARCHAR(50) UNIQUE,
    allergies TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Relación Paciente-Tutor (Muchos a Muchos)
CREATE TABLE IF NOT EXISTS relations (
    relation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INT,
    guardian_id INT,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE CASCADE,
    FOREIGN KEY (guardian_id) REFERENCES guardians(guardian_id) ON DELETE CASCADE
);

-- Esquema Oficial de Vacunación
CREATE TABLE IF NOT EXISTS vaccination_scheme (
    id_scheme INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaccine_id INT,
    dose_number VARCHAR(50) NOT NULL,
    ideal_age_months INT NOT NULL,
    min_interval_days INT DEFAULT 0,
    FOREIGN KEY (vaccine_id) REFERENCES vaccines(id_vaccine) ON DELETE CASCADE
);

-- Registro de Aplicaciones (Lo que sucede en la clínica)
CREATE TABLE IF NOT EXISTS vaccination_records (
    record_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INT,
    vaccine_id INT,
    worker_id INT,
    applied_date DATE NOT NULL,
    dose_applied VARCHAR(50),
    lot_number VARCHAR(50),
    clinic_location VARCHAR(100),
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    FOREIGN KEY (vaccine_id) REFERENCES vaccines(id_vaccine),
    FOREIGN KEY (worker_id) REFERENCES workers(worker_id)
);

-- Tabla de Beacons
CREATE TABLE IF NOT EXISTS beacons (
    id_beacon INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36),
    major INT,
    minor INT,
    lugar VARCHAR(100),
    estado VARCHAR(10) CHECK (estado IN ('Online', 'Offline')),
    patient_id INT REFERENCES patients(patient_id)
);

-- Logs de escaneo BLE
CREATE TABLE IF NOT EXISTS scan_logs (
    log_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INT REFERENCES patients(patient_id),
    uuid VARCHAR(36),
    major INT,
    minor INT,
    rssi INT,
    scanned_at TIMESTAMP,
    source_device VARCHAR(30)
);

DROP FUNCTION IF EXISTS pacientes(INT);
CREATE OR REPLACE FUNCTION pacientes(p_patient_id INT)
RETURNS TABLE (
    id_paciente INT,
    nombre_paciente TEXT,
    fecha_nacimiento DATE,
    vacunas_aplicadas TEXT,
    tipo_sangre VARCHAR(3),
    alergias TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        p.patient_id AS id_paciente,
        CONCAT(p.first_name, ' ', p.last_name) AS nombre_paciente,
        p.birth_date AS fecha_nacimiento,
        STRING_AGG(DISTINCT v.name, ', ' ORDER BY v.name) AS vacunas_aplicadas,
        p.blood_type AS tipo_sangre,
        p.allergies AS alergias
    FROM patients p
    LEFT JOIN vaccination_records vr ON vr.patient_id = p.patient_id
    LEFT JOIN vaccines v ON v.id_vaccine = vr.vaccine_id
    WHERE p.patient_id = p_patient_id
    GROUP BY p.patient_id, p.first_name, p.last_name, p.birth_date, p.blood_type, p.allergies;
END;
$$;

DROP FUNCTION IF EXISTS vacunas_aplicadas_por_paciente(INT);
CREATE OR REPLACE FUNCTION vacunas_aplicadas_por_paciente(p_patient_id INT)
RETURNS TABLE (
    id_vacuna INT,
    nombre_vacuna VARCHAR(100),
    fecha_aplicacion DATE,
    nombre_aplicador TEXT,
    fecha_proxima_dosis DATE,
    observaciones TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    WITH esquema_ordenado AS (
        SELECT
            vs.vaccine_id,
            vs.dose_number,
            vs.min_interval_days,
            ROW_NUMBER() OVER (
                PARTITION BY vs.vaccine_id
                ORDER BY vs.ideal_age_months, vs.id_scheme
            ) AS orden_dosis
        FROM vaccination_scheme vs
    ),
    resumen_vacuna AS (
        SELECT
            vr.patient_id,
            vr.vaccine_id,
            COUNT(*) AS dosis_aplicadas,
            MAX(vr.applied_date) AS fecha_ultima_aplicacion,
            (ARRAY_AGG(CONCAT_WS(' ', w.name, w.lastname) ORDER BY vr.applied_date DESC))[1] AS aplicador_ultimo,
            STRING_AGG(DISTINCT ('Lote: ' || COALESCE(vr.lot_number, 'N/A')), '; ') AS observaciones
        FROM vaccination_records vr
        LEFT JOIN workers w ON w.worker_id = vr.worker_id
        WHERE vr.patient_id = p_patient_id
        GROUP BY vr.patient_id, vr.vaccine_id
    )
    SELECT
        rv.vaccine_id AS id_vacuna,
        v.name AS nombre_vacuna,
        rv.fecha_ultima_aplicacion AS fecha_aplicacion,
        rv.aplicador_ultimo AS nombre_aplicador,
        CASE
            WHEN eo_siguiente.vaccine_id IS NULL THEN NULL
            ELSE (rv.fecha_ultima_aplicacion + (COALESCE(eo_siguiente.min_interval_days, 0) * INTERVAL '1 day'))::DATE
        END AS fecha_proxima_dosis,
        rv.observaciones
    FROM resumen_vacuna rv
    INNER JOIN vaccines v ON v.id_vaccine = rv.vaccine_id
    LEFT JOIN esquema_ordenado eo_siguiente
        ON eo_siguiente.vaccine_id = rv.vaccine_id
       AND eo_siguiente.orden_dosis = rv.dosis_aplicadas + 1
    ORDER BY v.name;
END;
$$;

DROP FUNCTION IF EXISTS proximas_citas_vacunacion(INT);
CREATE OR REPLACE FUNCTION proximas_citas_vacunacion(p_patient_id INT)
RETURNS TABLE (
    id_paciente INT,
    nombre_paciente TEXT,
    id_vacuna INT,
    nombre_vacuna VARCHAR(100),
    proxima_dosis VARCHAR(50),
    fecha_cita DATE,
    estado_cita TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    WITH esquema_ordenado AS (
        SELECT
            vs.vaccine_id,
            vs.dose_number,
            vs.min_interval_days,
            ROW_NUMBER() OVER (
                PARTITION BY vs.vaccine_id
                ORDER BY vs.ideal_age_months, vs.id_scheme
            ) AS orden_dosis
        FROM vaccination_scheme vs
    ),
    resumen_vacuna AS (
        SELECT
            vr.patient_id,
            vr.vaccine_id,
            COUNT(*) AS dosis_aplicadas,
            MAX(vr.applied_date) AS fecha_ultima_aplicacion
        FROM vaccination_records vr
        WHERE vr.patient_id = p_patient_id
        GROUP BY vr.patient_id, vr.vaccine_id
    )
    SELECT
        p.patient_id AS id_paciente,
        CONCAT(p.first_name, ' ', p.last_name) AS nombre_paciente,
        v.id_vaccine AS id_vacuna,
        v.name AS nombre_vacuna,
        eo_siguiente.dose_number AS proxima_dosis,
        (rv.fecha_ultima_aplicacion + (COALESCE(eo_siguiente.min_interval_days, 0) * INTERVAL '1 day'))::DATE AS fecha_cita,
        CASE
            WHEN (rv.fecha_ultima_aplicacion + (COALESCE(eo_siguiente.min_interval_days, 0) * INTERVAL '1 day'))::DATE >= CURRENT_DATE
                THEN 'Cita programable/existente'
            ELSE 'Sin cita vigente'
        END AS estado_cita
    FROM patients p
    INNER JOIN resumen_vacuna rv ON rv.patient_id = p.patient_id
    INNER JOIN vaccines v ON v.id_vaccine = rv.vaccine_id
    LEFT JOIN esquema_ordenado eo_siguiente
        ON eo_siguiente.vaccine_id = rv.vaccine_id
       AND eo_siguiente.orden_dosis = rv.dosis_aplicadas + 1
    WHERE p.patient_id = p_patient_id
      AND eo_siguiente.vaccine_id IS NOT NULL
      AND (rv.fecha_ultima_aplicacion + (COALESCE(eo_siguiente.min_interval_days, 0) * INTERVAL '1 day'))::DATE >= CURRENT_DATE
    ORDER BY fecha_cita;
END;
$$;